apiVersion: v1
kind: Namespace
metadata:
  name: online-boutique
  labels:
    app.kubernetes.io/name: online-boutique
    app.kubernetes.io/part-of: online-boutique
    app.kubernetes.io/managed-by: kubectl
    environment: production

    # Enable automatic Istio sidecar injection
    istio-injection: enabled